### ISSUE TITLE
Hacktoberfest2021

### ISSUE THREAD

**Issue by wafarifki** [wafarifki/Xiboba-Landing-Page#2]
fork, do change and pull request if you want to participate to hacktoberfest 2021

**Comment by shivprime94** [comment]
Hi, I want to update your button which is not adjusting its size according to width of the screen assign me this work.
I am interested

**Comment by wafarifki** [comment]
> Hi, I want to update your button which is not adjusting its size according to width of the screen assign me this work. I am interested

yes, please update. and i will check and merge bro

**Comment by shivprime94** [comment]
Hi @wafarifki if you have any task let me know!

**Comment by wafarifki** [comment]
> Hi @wafarifki if you have any task let me know!

okay bro i will tell you if i have any task again

**Comment by Raj-Thombare** [comment]
hey i want to contribute to your project!

**Comment by wafarifki** [comment]
> hey i want to contribute to your project!

yes, you can. please star and fork this repo. build simple any program with any language you like, pull request and don't forget to put your name in CONTRIBUTING.md

thanks for participate the event with this repo

**Comment by Shubham56-droid** [comment]
hi @wafarifki I would like to contribute to your project can I?

**Comment by Shubham56-droid** [comment]
Can i add a preloader to your website.

**Comment by wafarifki** [comment]
> Can i add a preloader to your website.

yes you can bro,please add

**Comment by Shubham56-droid** [comment]
hi bro @wafarifki I have added an awesome preloader to ur website pls do check it bro and merge my pr hope u like my work #5

**Comment by wafarifki** [comment]
> hi bro @wafarifki I have added an awesome preloader to ur website pls do check it bro and merge my pr hope u like my work #5

yeah i like it...thank you bro :) very cool & awesome.

**Comment by Shubham56-droid** [comment]
hi bro i would like to work on  UI little bit pls assign this issue to me

**Comment by dwidhanis** [comment]
hello! i want to add daftar menu page

**Comment by wafarifki** [comment]
> hello! i want to add daftar menu page

yes please do it bro

**Comment by rounit08** [comment]
Can I take this?

**Comment by wafarifki** [comment]
> Can I take this?

yeah you can bro

**Comment by rounit08** [comment]
> > Can I take this?
> 
> yeah you can bro

Assign me then :)

**Comment by abhijeet-crypto** [comment]
i would like to work on this

**Comment by manasvip01** [comment]
I would like to work on this!!

**Comment by wafarifki** [comment]
> i would like to work on this

please do it

**Comment by wafarifki** [comment]
> I would like to work on this!!

please do it and i will review it

**Comment by manasvip01** [comment]
Can I add any program in c++ language?

**Comment by KIET7UKE** [comment]
I want to contribute in your repo...Can i add codechef solutions ...

**Comment by wafarifki** [comment]
> I want to contribute in your repo...Can i add codechef solutions ...

yeah you can bro please add

**Comment by KIET7UKE** [comment]
@wafarifki Bro i have added 3 proper solutions of codechef october cooktime...plese check and accept pull request and please add a label of hacktober fest 2021 accepted so that it will be accepted for hacktobefest...please sir merge it soon!

**Comment by wafarifki** [comment]
> @wafarifki Bro i have added 3 proper solutions of codechef october cooktime...plese check and accept pull request and please add a label of hacktober fest 2021 accepted so that it will be accepted for hacktobefest...please sir merge it soon!

done bro

**Comment by KIET7UKE** [comment]
@wafarifki bro can you please add labels in my codes.

**Comment by wafarifki** [comment]
> @wafarifki bro can you please add labels in my codes.

yeah done..you can check in your pr

**Comment by KIET7UKE** [comment]
Yah sure wait let me add😊

**Comment by Chinmayk2002** [comment]
I would like to work on this

**Comment by wafarifki** [comment]
> I would like to work on this

yeah you can
